server:
  port: 18080
dubbo:
  application:
    name: tanhua-app
  registry:
    address: zookeeper://192.168.136.160:2181
    check: false
    timeout: 500000
  scan:
    base-packages: com.itheima.app


# 探花配置
tanhua:
  sms:
    access-key: LTAI4G3uHmEsKn5okn1wWYk6
    secret: ZhTbkMEuFhPmRTQvPpQJSRfiY41yCg
    sign-name: 黑马旅游网
    template-code: SMS_170836451
  oss:
    accessKey: LTAI4G3uHmEsKn5okn1wWYk6
    secret: ZhTbkMEuFhPmRTQvPpQJSRfiY41yCg
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: tanhua-gxm
    url: https://tanhua-gxm.oss-cn-beijing.aliyuncs.com
  aip:
    appId: 23185047
    apiKey: sAXm3wjOaTL0KyqIvVpD4ODN
    secretKey: i3DrQhOn5m37hEnBAOdpLamtFUZaGZhl
  huanxin:
    url: http://a1.easemob.com/
    orgName: 1129210104046247
    appName: tanhua
    clientId: YXA6fvvYD7wGTOSdUMtAEAPPXw
    clientSecret: YXA63DEHnf4Bndlo38-XJPVrn317USI

# redis配置
spring:
  redis:
    host: 192.168.136.160
    port: 6379
    database: 0
    #文件上传
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

# fastdfs配置
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  thumb-image: #缩略图生成参数
    width: 150
    height: 150
  tracker-list: 192.168.136.160:22122 #TrackerList参数,支持多个
  web-server-url: http://192.168.136.160:8888/ # nginx访问路径


rocketmq:
  name-server: 192.168.136.160:9876
  producer:
    group: tanhua-app
    send-message-timeout: 30000

