server:
  port: 18083
dubbo:
  application:
    name: tanhua-admin
  registry:
    address: zookeeper://192.168.136.160:2181
    check: false
    timeout: 500000

spring:
  redis:
    host: 192.168.136.160
    port: 6379
    database: 0

rocketmq:
  name-server: 192.168.136.160:9876

tanhua:
  huawei:
    username: tanhua
    password: tanhua123
    project: cn-north-1
    domain: odd466b7514015027768
    # 图片检测内容 politics：是否涉及政治人物的检测，terrorism：是否包含涉政暴恐元素的检测，porn：是否包含涉黄内容元素的检测，ad：是否包含广告的检测（公测特性），all：包含politics、terrorism和porn三种场景的检测
    cagegoriesImage: politics,terrorism,porn
    # 文字检测内容 politics：涉政，porn：涉黄，ad：广告，abuse：辱骂，contraband：违禁品，flood：灌水
    cagegoriesText: politics,porn,ad,abuse,contraband,flood